version: '3.8'

services:
    nginx_ex28:
      image: nginx
      volumes:
        - type: bind
          source: ./nginx.conf
          target: /etc/nginx/nginx.conf
      ports:
        - "80:80"
      environment:
        - NGINX_HOST=http://localhost
        - NGINX_PORT=80
      depends_on:
        - backend
        - frontend

    db_ex28:
      image: postgres
      ports:
        - 5432:5432
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db_ex28
      volumes:
        - type: bind
          source: ./database
          target: /var/lib/postgresql/data

    backend:
      ports:
        - 8080:8080
      container_name: ex28-backend
      build:
        context: ./material-applications/example-backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db_ex28
    
    frontend:
      ports:
        - 5000:5000
      container_name: ex28-frontend
      build:
        context: ./material-applications/example-frontend
     
    redis:
      image: redis
      ports:
        - 6379:6379
      container_name: redis_ex28
      
volumes:
  database:

#git clone https://github.com/docker-hy/material-applications.git
#cp front/Dockerfile material-applications/example-frontend
#cp back/Dockerfile material-applications/example-backend
#docker compose up
